### PR TITLE
WIP: remove power state & lots of code cleanup

### PR DESCRIPTION
**Pull request by smichel17**
This is what ended up happening to #36 (it also ends up addressing some of #70). I thought (and more importantly, observed) a bit more and had these conclusions:
- The power switch was a frequent point of confusion until you added the intro screen
- I never touch the power switch apart from the initial install.
- Having the app on manual is just as good a guarantee that Red Moon won't run anything on your phone as having the app be powered off.
- "Powered off" isn't actually reflected in the backend; it's an illusion we create for the user. In actuality, 'Paused' is just as much off as 'Off'.

Here's changes I made or would like to make. I was planning on implementing all of these, but ran out of time and I'm not sure when I'll have more.
- [x] Move email and github links into an overflow menu. They're not settings.
- [x] Remove the FAB. It covers up the dark theme switch.
- [x] Modify the app bar switch to toggle the filter instead of "power state"
  - [x] Cut "power state" out of the code
  - [x] Make the slider toggle the filter and respond to filter toggles
  - [x] Attempting to turn on the filter without the permission should show a popup with a brief explanation before taking you to the settings.
  - [x] Bug: the switch does not work unless the filter has been started before.
  - [ ] Bug: The switch is set incorrectly when the activity is cold launched.
    - Going home and then returning to red moon (or otherwise calling onCreateOptionsMenu) will set the switch correctly.
    - Once the switch is set correctly, you can replicate the bug by closing red moon via the app switcher (so the process is killed), then opening it again. It will be set incorrectly regardless of whether the filter is on or not.
  - [x] Bug: App to asks for permission before the user toggles the switch.
  - [x] Bug: Inconsistent behavior when toggled while filter is mid-animation

Strings update:
- All references to "Power off" removed
- All references to "pause" -> "Stop"
- All references to "resume", "turn on", or "enable" -> "Start"
- `Automatically suspend filter in secure apps` -> `Pause in secure apps`

### CODE REVIEW

**Comment by smichel17** [comment]
>Thanks for making this!

>If I install this version on my device, after enabling the switch in the app bar, when I press 'Resume' in the notification, while the Red Moon Activity is still running, the switch in the app bar is disabled and the filter is immediately turned off. The switch in the app bar seems to try to turn back on every second or so, but is immediately disabled. The notification is still visible at this point though. Enabling the filter with the 'Resume' button if the Activity is not in the foreground does work though. Do you have any idea what may be causing this?

>PS: I've merged pulled all the commits from master to feature_stop_state, so that it is even with master now. However, Github is still showing all the 119 commits and changes. Maybe Github needs a while to update this or something?

When you tap a switch, the switch's state gets toggled independent of the callback attached to it.

When the filter gets toggled automatically (or manually from the notification), the switch gets set to the "correct" state. 

There was some code related to ignoring the next toggle; I don't remember if I removed it or not.

I think it is the result of a weird interaction between these parts. I don't know what that interaction is but I figure it'll probably be easiest just to rewrite it all so that there's one function that checks if the switch is in the right state and update it if not, then call that everywhere we need to.

**Comment by raatmarien** [comment]
I agree, rewriting it is probably warranted.

**Comment by smichel17** [comment]
Found the interaction. At first I thought it was simple, then I thought it was really complicated, then it turned out to be fairly simple, lol. No need to rewrite. There were actually two infinite loops:

1. The callback on switch toggle can't tell whether the user toggled it or we did, so it was sending an intent every time it was toggled, which caused it to be toggled again.
  - The fix: check if the switch is in the same state as the filter. If it is, that means we set it internally and we don't need to send an intent.
- I was setting the switch to be the SAME as the pause state -- on if it's paused and off if it's not paused, which made my logic above always think it was user input, and send the intent.

**Comment by smichel17** [comment]
Almost ready to merge...

**Comment by smichel17** [comment]
There are bugs in fd6d091; I will probably be rebasing; pull at your own risk

**Comment by smichel17** [comment]
Fixing the last bug: For some reason, at line 149 of ShadesActivity.java, `mSettingsModel.getShadesPauseState()` is returning the wrong value; it thinks the filter is not paused when it is paused. That is, line 113 of SettingsModel.java, `mSharedPreferences.getBoolean(mPauseStatePrefKey, false);`, is returning false when it should be returning true. Changing the default value This is NOT an issue of the settings not being initialized and returning the call to be `mSharedPreferences.getBoolean(mPauseStatePrefKey, true);` had no effect, so it's legitimately getting the wrong value, not returning the default. 

Recreating the switch after the activity has been created (eg, by changing the `dark theme` setting) will set the switch correctly. The first time the activity is started, the switch will be set incorrectly regardless of whether the filter is on or off. You can reproduce by swiping red moon away in the application switcher, then re-opening it.

@raatmarien Do you have any idea what this could be? I'm rather stumped. Once this bug is fixed, this MR is ready to merge!

**Comment by smichel17** [comment]
@raatmarien Ready to merge. Would you like me to do a review of this detailing the changes so it's easier for you to see what you're merging?

**Comment by smichel17** [comment]
@raatmarien Ready to merge. Would you like me to do a review of this detailing the changes so it's easier for you to see what you're merging?

**Comment by smichel17** [comment]
I'd wait to merge to master until I have time to send a PR for #90, though.

**Comment by smichel17** [comment]
Ack, harmless fix wasn't actually harmless

**Comment by smichel17** [comment]
I believe the bug is related to some of the changes I made in ScreenFilterPresenter, where the pause state isn't always being correctly set in the settings.

**Comment by smichel17** [comment]
I am going to do #90 and #93 before I fix this bug, as I am stumped and maybe eventbus will simplify the code enough that I can figure it out.

**Comment by smichel17** [comment]
Closing this because converting to kotlin was going to make merging tricky, so I merged this into #95

**Pull request closed without merging**
