### PR TITLE
Updates + Travis

### PR DESCRIPTION
**Pull request by Jawnnypoo**
This updates the project to use API 25 things (support lib, SDK, build tools)

This also adds a travis configuration (you will still need to enable travis at travis-ci.org)

Also, added a plugin to detect new versions. Just run `./gradlew dependencyUpdates`

### CODE REVIEW

**Comment by Jawnnypoo** [comment]
Any thoughts here, @raatmarien ?

**Comment by smichel17** [comment]
@Jawnnypoo I'm not @raatmarien, but my thoughts are:

- Removing the old Eclipse file makes sense.
- Should do some testing on an API 25 emulator, otherwise that seems reasonable.
- I like that the gradle version plugin makes me less dependent on Android Studio.
- I don't see where Travis comes in that handy. Sure, it's nice to be able to see whether a PR breaks the build before merging, but if there's any substantial PR, I'd pull and test a little before merging anyway. Likewise with any feature I'd write myself.

**Comment by Jawnnypoo** [comment]
Travis is great for when people make PRs that you may not want to review manually, but have a machine run tests before merging. Something exactly like this PR. There is not much to it, but it would be great to have the assurance that nothing breaks in Unit tests. Although this app is lacking any tests right now, it might have them in the future, and that is where Travis comes into play. 

Needless to say, most open source Android libraries and projects at least have Travis (or some other CI) set up in some capacity to check builds, so I figured it would be useful

**Comment by smichel17** [comment]
I see the value of Travis in general, but remain unconvinced it will be useful right now. 

That said, having an unused config file just sitting around in the repo is not a terrible problem.

**Comment by raatmarien** [comment]
Thanks for this PR @Jawnnypoo :+1: , the new version detection with Gradle looks really neat! As for Travis, I'm not sure if it is worth it for Red Moon right now, but it's nice to have the option to enable it.

**Pull request merged**
