### PR TITLE
remove stop state; just pause state now. remove fab.

### PR DESCRIPTION
**Pull request by smichel17**
This is what ended up happening to #36. I thought (and more importantly, observed) a bit more and had these conclusions:

- The power switch was a frequent point of confusion until you added the intro screen
- I never touch the power switch apart from the initial install.
- Having the app on manual is just as good a guarantee that Red Moon won't run anything on your phone as having the app be powered off.
- "Powered off" isn't actually reflected in the backend; it's an illusion we create for the user. In actuality, 'Paused' is just as much off as 'Off'.

Here's changes I made or would like to make. I was planning on implementing all of these, but ran out of time and I'm not sure when I'll have more.

- [x] Move email and github links into an overflow menu. They're not settings.
- [x] Remove the FAB. It covers up the dark theme switch.
- Modify the app bar switch to toggle the filter instead of "power state"
  - [x] Cut "power state" out of the code
  - [Incomplete] Make the slider toggle the filter and respond to filter toggles
  - [ ] Attempting to turn on the filter without the permission should be a similar interaction to enabling automatic suspend in secure apps: there's a popup with a brief explanation, then you go to the other screen, then you return and the app picks up where it left off, with the switch enabled.
- [ ] Separate the filter toggle into two switches instead of a drop-down menu:
  - [ ] `Automatic toggle` switches between manual and automatic modes
  - [ ] `Times from sun` (Probably there's a better phrasing for that but I'm really tired right now) switches between custom and location-based times. This preference is **disabled and hidden** when `Automatic toggle` is off.
  - [ ] `Location` should be **removed**.(actual implementation, just change the location setting so it extends a switchprefrence instead of a plain old preference)
    - [ ] Its summary text should be moved to the `Location from sun` switch
    - When the app is open in the foreground and the setting is enabled, keep a lock on location the entire time. It'll drain the battery but, as you pointed out in another thread, people really shouldn't be spending much time in the activity anyway.

Strings update:
- All references to "Power off" removed
- All references to "pause" -> "Stop"
- All references to "resume", "turn on", or "enable" -> "Start"
- `Automatically suspend filter in secure apps` -> `Pause in secure apps`

### CODE REVIEW

**Comment by smichel17** [comment]
haha, those commits.

**Comment by raatmarien** [comment]
Thanks for making this!

If I install this version on my device, after enabling the switch in the app bar, when I press 'Resume' in the notification, while the Red Moon Activity is still running, the switch in the app bar is disabled and the filter is immediately turned off. The switch in the app bar seems to try to turn back on every second or so, but is immediately disabled. The notification is still visible at this point though. Enabling the filter with the 'Resume' button if the Activity is not in the foreground does work though. Do you have any idea what may be causing this?

PS: I've merged pulled all the commits from master to feature_stop_state, so that it is even with master now. However, Github is still showing all the 119 commits and changes. Maybe Github needs a while to update this or something?

**Comment by smichel17** [comment]
When you tap a switch, the switch's state gets toggled independent of the callback attached to it.

When the filter gets toggled automatically (or manually from the notification), the switch gets set to the "correct" state. 

There was some code related to ignoring the next toggle; I don't remember if I removed it or not.

I think it is the result of a weird interaction between these parts. I don't know what that interaction is but I figure it'll probably be easiest just to rewrite it all so that there's one function that checks if the switch is in the right state and update it if not, then call that everywhere we need to.

**Comment by smichel17** [comment]
I'm not sure; I'll just close & remake this PR.

**Pull request closed without merging**
