### PR TITLE
Translate and some changes

### PR DESCRIPTION
**Pull request by kuoruan**

### CODE REVIEW

**Comment by raatmarien** [comment]
Thanks for contributing!

In you 3rd commit (e55539d - Delete namespace to fix gradle error) you delete some tags that inform the lint. Because of this the lint issues a lot of warnings and an error. Could you explain why you removed these tags?

**Comment by kuoruan** [comment]
These namespace caused a lot of error in my version of android studio... My Android Studio version is 2.2 Preview 6.

**Comment by raatmarien** [comment]
Hmm, that's very weird. Thanks for the further information, I will look into it.

**Comment by pylerSM** [comment]
Same issue, just fresh fork imported to AS and tons of errors.

**Comment by smichel17** [comment]
@kuoruan I wasn't sure how to proceed on this one since some of it is still relevant but some of it is not. If you're still interested in getting the translation added, if you do it [here](https://hosted.weblate.org/projects/red-moon/strings/zh_RCN/) on weblate, the changes will be merged automatically. Note: I'm planning on making a few phrasing changes tonight, as #121 describes.

**Comment by kuoruan** [comment]
This pull request is too old, so I closed it. I haven't seen this project for a long time. I notice that you have changed to kotlin. I well keep watching this project.

**Pull request closed without merging**
