### PR TITLE
upgrade target SDK to 25.0.0 and update gradle to 2.2.2

### PR DESCRIPTION
**Pull request by smichel17**

### CODE REVIEW

**Comment by Kasijjuf** [comment]
FWIW, I personally don't think the target SDK version should be bumped to 25 on the master branch until after Android 7.1 gets pushed to AOSP.

**Comment by smichel17** [comment]
That's fair. I'll change this to 24.

**Comment by raatmarien** [comment]
The linter was giving some new errors because of these changes, but those are fixed now :+1:

**Comment by smichel17** [comment]
Yeah, I always forget to check lint since I don't often use android studio. Oops.

**Pull request merged**
